LuckyBlocks:
  Orange:
    Name: ''
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2RkMWU2YmQyMTVhZmE1ZTY3MzI4NWFmYWNiODVlYjhkMGY3OWE1YjQ2YzU0MzJkNmZlZWQ2NjA5N2M1MTI0OCJ9fX0='
    UUID: '9fb9a082-e047-11eb-ba80-0242ac130004'
    GlassBlock: 'ORANGE_STAINED_GLASS'
    DropRate: 100
    Spawners:
      - 'IRON_INGOT'
    Drops:
      - 'tower'