LuckyBlocks:
  Orange:
    Name: '&6Orange Lucky Block'
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmZkY2ZiNDAwOTc2YmY3M2VjMzJjMWI5OTYyYzgzMGZjM2Q3MDA2ZDc0OWY4ZjNkYTNiNmUwZmI4MjkwOWIyOCJ9fX0='
    UUID: '9fb9a082-e047-11eb-ba80-0242ac130004'
    GlassBlock: 'ORANGE_STAINED_GLASS'
    DropRate: 100
    DropAmount: 2
    ItemCap: 40
    Spawner: 'IRON_INGOT'
    Drops:
      - 'tower'
  Blue:
    Name: '&1Blue Lucky Block'
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTQ1ZTczNDM1MDAzZmE1NzZlYmE0Yjc4ZDk4MDg4NDQ5ZGQ4NDJhODJhZWRlMDNhMzlkNzdmMzk4NDE4NjBiNyJ9fX0='
    UUID: '92b72e36-e0d3-11eb-ba80-0242ac130004'
    GlassBlock: 'BLUE_STAINED_GLASS'
    DropRate: 200
    DropAmount: 1
    ItemCap: 20
    Spawner: 'GOLD_INGOT'
    Drops:
      - 'tower'
  Green:
    Name: '&1Blue Lucky Block'
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTk5N2QzNTVlMjNmNGRhN2JlNjkxMzllZWMxNTg2MDljNzBiZGFiNGJiOTNlM2ZhODI2NzlkNTNiMmRiZGZkIn19fQ='
    UUID: '92b72e36-e0d3-11eb-ba80-0242ac130004'
    GlassBlock: 'GREEN_STAINED_GLASS'
    DropRate: 200
    DropAmount: 1
    ItemCap: 6
    Spawner: 'DIAMOND'
    Drops:
      - 'tower'
  Black:
    Name: '&1Blue Lucky Block'
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzcxOTMwMjc4ZjAyOWM1Nzc4Yzg1YzA0NzVhMzdmYWM4YWNkMzg1MDc0MmFhZTZhMzU0MmFjZGU0NDg3ZDYzIn19fQ='
    UUID: '92b72e36-e0d3-11eb-ba80-0242ac130004'
    GlassBlock: 'BLACK_STAINED_GLASS'
    DropRate: 200
    DropAmount: 1
    ItemCap: 4
    Spawner: 'DIAMOND'
    Drops:
      - 'tower'
  Red:
    Name: '&1Blue Lucky Block'
    Texture: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWI0ZDNjNjk2NDllMjU3MTZjYTA5MzE3Y2I0ZGJhYzE5NTU1MjI5ZjY2YmYxMWJmZWIwYzc1YjdmZTg3ODUzIn19fQ='
    UUID: '92b72e36-e0d3-11eb-ba80-0242ac130004'
    GlassBlock: 'RED_STAINED_GLASS'
    DropRate: 200
    DropAmount: 1
    ItemCap: 2
    Spawner: 'EMERALD'
    Drops:
      - 'tower'